
version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert_rules.yml:/etc/prometheus/alert_rules.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"

  alertmanager:
    image: prom/alertmanager
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    ports:
      - "9093:9093"

  node_exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"

  webhook:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./agent:/app/agent
      - ./webhook:/app
      - /var/log:/var/log:ro
      - ./webhook/incident_logs.txt:/app/incident_logs.txt
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    restart: always

  agent:
    build:
      context: ./agent
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./agent:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - ./webhook/incident_logs.txt:/app/incident_logs.txt
      - /var/log:/var/log:ro
    env_file:
      - .env
    depends_on:
      - prometheus
      - webhook

