
version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - /etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /etc/prometheus/alert_rules.yml:/etc/prometheus/alert_rules.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"

  alertmanager:
    image: prom/alertmanager
    volumes:
      - /etc/prometheus/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    ports:
      - "9093:9093"

  node_exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"

  webhook:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./agent:/app/agent
    env_file:
      - .env
    restart: always

  agent:
    image: python:3.9-slim
    working_dir: /app
    volumes:
      - ./agent:/app
    command: python3 opsbot.py
    depends_on:
      - prometheus
      - webhook
